src/partials/body-scripts.hbs
Search for only one version of the interface (Current selected or stable7)
=> Add filters to docsearch

src/helpers/capitalizeFirstLetter.js, src/partials/head-meta.hbs
exclude ROOT dir
capitalise first letter
=> feat: improve elastic tag content

src/js/06-collapsebox.js
Fix selector when there's more than one box on a page.
=> fix: collapsebox selector

src/js/11-elastic-search.js
- Limit suggestions query to headings and keywords
- Auto focus input field when displayed
- Add keyboard shortcut to toggle search
=> feat: improve search

src/css/header.css, src/css/search.css
Fix search bar overflow
Increase lang picker item spacing
=> fix: header styling

src/partials/nav-explore.hbs
Reverts plentymarkets/plenty-docs-ui#111
=> Revert "feat: hide nav explore if nothing to display"

src/css/dark-theme.css, src/css/docsearch.css, src/css/light-theme.css, src/css/site-light-theme.css, src/css/site.css, src/js/11-elastic-search.js, src/partials/body-scripts.hbs, src/partials/header-content-developers.hbs
Reverts plentymarkets/plenty-docs-ui#115
=> Revert "Dcj/230785"

src/partials/head-scripts.hbs
=> fix: update cdn source

src/css/vars.css
- Update nav width to 18%
- Update toc width to 18%
=> feat: update nav width

src/css/base.css, src/partials/head-styles.hbs
Imports additional font weights
=> fix: italics font weight

src/js/11-elastic-search.js
- Change decodeURI to decodeURIComponent
=> fix: special characters in search query

src/partials/head-scripts.hbs
- Add Mathjax lib
- Doesn't include AsciiMath
=> fix: stem support

src/css/fonts.css
=> fix: material icons vertical align

src/css/header.css, src/partials/header-content-knowledge.hbs
- Remove icon
- Update dropdown offset
=> fix: language select styling

src/css/doc.css, src/css/vars.css
=> fix: support additional table options

src/css/pagination.css, src/partials/article.hbs
- Move pagination above feedback form
- Remove labels
=> fix: update pagination

src/css/doc.css, src/css/theme-blue.css, src/css/theme-petrol.css, src/css/theme-red.css
- Improves messaging in admonitions
- Updates colors
- Updates icons
- Removes caution block styling
=> feat: update admonition blocks

src/layouts/swagger.hbs
=> fix: swagger cdn source

preview-src/index.adoc, src/css/forum-info.css, src/css/site.css, src/lang/de-de.json, src/lang/en-gb.json, src/partials/article.hbs, src/partials/forum-info.hbs
=> feat: create forum info box

src/css/nav.css, src/css/responsive.css, src/css/vars.css
[AB#54466](https://dev.azure.com/plentymarkets/0af57df9-8662-4901-bb97-8e88b07ff0c9/_workitems/edit/54466)
- Update drawer position
=> fix: mobile navigation

src/layouts/homepage.hbs, src/partials/header-content-developers.hbs
- Add homepage tile
- Add header link
=> feat: add pwa-docs to developers
